# Site settings
title: æ›¦ç§‹çš„å°å±‹
SEOTitle: æ›¦ç§‹çš„å°å±‹ | DanLiu Blog
header-img: img/home-bg.jpg
email: liu_chengjia@qq.com
description: ""
keyword: "LCJ , Danliu , æ›¦ç§‹çš„å°å±‹ , æ›¦ç§‹ , æš®å¤æ›¦ç§‹ , danliu , @æ›¦ç§‹ , @æ›¦ç§‹çš„å°å±‹ , åšå®¢ , ä¸ªäººåšå®¢"
url: "https://blog.atdanliu.cn"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'
cdnurl: "https://cdn.jsdelivr.net/gh/DanLCJ/danblog@master"

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
#weibo_username:     huxpro
#zhihu_username:     huxpro
github_username:     DanLCJ
#twitter_username:   huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx
tencent_account:     583644186
instagram_username:  chengjialiu
email_username:      liu_chengjia@qq.com
bilibili_uid:        46881658


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  

# Valine
valine:
  enable: true                  #æ˜¯å¦å¼€å¯Valineè¯„è®º
  appId: HIn4FzoQuCddO8EyjClXtSSW-MdYXbMMI                  #ç”Ÿæˆçš„appId
  appKey: Mak2qKcTmqYxLw0feQQelpp8                          #ç”Ÿæˆçš„appKey
  serverURL: https://api.comment.atdanliu.cn
  placeholder: 'ä½ æ˜¯æˆ‘ä¸€ç”Ÿåªä¼šé‡è§ä¸€æ¬¡çš„æƒŠå–œ | á´¥â€¢Ì )âœ§'    #è¯„è®ºæ¡†å ä½æç¤ºç¬¦
  enableQQ: true                #æ˜¯å¦å¯ç”¨æ˜µç§°æ¡†è‡ªåŠ¨è·å–QQæ˜µç§°å’ŒQQå¤´åƒ
  recordIP: true                #æ˜¯å¦è®°å½•è¯„è®ºè€…IP

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: hux

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics
ba_track_id: 6fc29523f35d9f9a7c8ef0565a9b37ba
# Google Analytics
ga_track_id: 'UA-173392935-1'            # Format: UA-xxxxxx-xx
ga_domain: blog.atdanliu.cn



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: â€œäººç”Ÿæ˜¯ä¸€åœºè›¹åŒ–è¶ï¼Œ<br>ç£¨ç ºåå°†æ˜¯è‡ªç”±çš„æ‹¥æŠ±è“å¤©ã€‚"<br>â€œå½“ç„¶ï¼Œåœ¨é‚£ä¸€å¤©åˆ°æ¥ä¹‹å‰æˆ‘ä»¬éƒ½ä¸åº”è¯¥æ”¾å¼ƒï¼Œ<br>è¦å¯¹ç”Ÿæ´»å……æ»¡å¸Œæœ›ï¼Œå¯¹è‡ªå·±å……æ»¡è‡ªä¿¡ã€‚â€<br>â€œæ™šå®‰ï¼Œæ¯”å¿ƒã€‚ğŸ¤â€
sidebar-avatar: /img/geren.jpg       # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "DuDu",
        href: "https://blog.atdanliu.cn/jump.html?tpurl=https://lukejiang.netlify.app"
    },{
        title: "å°æ­ªç½‘ç»œ",
        href: "https://blog.atdanliu.cn/jump.html?tpurl=https://www.ixiaowai.cn/"
    },{
        title: "æ¢¨èŠ±å¸¦é›¨æ’­æ”¾å™¨",
        href: "https://blog.atdanliu.cn/jump.html?tpurl=https://music.m0x.cn/index/"
    },{
        title: "ä»Šæ—¥è¯—è¯",
        href: "https://blog.atdanliu.cn/jump.html?tpurl=https://www.jinrishici.com"
    },{
        title: "æ¢¦ç‹¬åŸ",
        href: "https://blog.atdanliu.cn/jump.html?tpurl=https://www.datealive.top/"
    },{
        title: "å…è´¹å¤‡æ¡ˆåŸŸå",
        href: "https://blog.atdanliu.cn/jump.html?tpurl=http://cc.1xie.xyz/"
    },{
        title: "Seeker",
        href: "https://blog.atdanliu.cn/jump.html?tpurl=https://snow.js.org/"
    }
]
